### ISSUE TITLE
I can't biuld project

### ISSUE THREAD

**Issue by dm-korottsev** [mahen-github/spark-scala-gradle-bootstrap#1]
Hello! Thanks for the template project! Could you help me? I can't biuld it with Gradle :(

Included build '/home/dmitry/spark_playground/spark-scala-gradle-bootstrap-main/plugin' does not exist.

* Exception is:
org.gradle.api.InvalidUserDataException: Included build '/home/dmitry/spark_playground/spark-scala-gradle-bootstrap-main/plugin' does not exist.

**Comment by mahen-github** [comment]
Fixed it. can you check again pls?
